version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    command: postgres
    ports:
      - "5433:5432"
  api:
    restart: always
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/var/app/judge-server
      - cached_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
volumes:
  db_data:
  cached_gems: