version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - judge_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  api:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/var/app/judge-server
      - cached_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
volumes:
  judge_data:
  cached_gems: