version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    command: postgres
    ports:
      - "5433:5432"
  api:
    restart: always
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${RAILS_PORT} -b '0.0.0.0'"
    volumes:
      - ./server:/var/app/judge-server
      - cached_gems:/usr/local/bundle/
    ports:
      - ${RAILS_PORT}:${RAILS_PORT}
    environment:
      RAILS_ENV: development
      RAILS_PORT: ${RAILS_PORT}
    env_file:
      - .env
  client:
    restart: always
    build: ./client
    command: yarn start
    volumes:
      - ./client/src:/var/app/judge-client/src
      - ./client/public:/var/app/judge-client/public
      - ./client/node_modules:/var/app/judge-client/node_modules
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    environment:
      PORT: ${REACT_PORT}
    env_file:
      - .env
volumes:
  db_data:
  cached_gems: